---
title: "GETM"
author: "Jens Daniel Müller und Bernd Schneider"
date:  "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  workflowr::wflow_html:
    number_sections: true
    toc_depth: 3
    toc_float:
      collapsed: false
editor_options:
  chunk_output_type: console
---


```{r global_options, include = FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
```

```{r packages}
library(tidyverse)
library(ncdf4)
library(lubridate)
library(here)
library(patchwork)
library(metR)
library(scico)
```


```{r ggplot_theme, include = FALSE}
theme_set(theme_bw())
```


```{r subsetting_criteria}

# route
select_route <- "E"

#depth range to subset GETM 3d files
# d1_shallow <- 0
# d1_deep <- 25

# date limits
start_date <- "2018-04-01"
end_date <- "2018-05-22"

```

# Read GETM data

```{r read_gt_2d_mld_wind, eval=FALSE}

nc_2d <- nc_open(here("data/GETM", "Finnmaid.E.2d.2018.nc"))
#print(nc_2d)

lat <- ncvar_get(nc_2d, "latc")

time_units <- nc_2d$dim$time$units %>%     #we read the time unit from the netcdf file to calibrate the time 
    substr(start = 15, stop = 33) %>%   #calculation, we take the relevant information from the string
    ymd_hms()                           # and transform it to the right format
t <- time_units + ncvar_get(nc_2d, "time") # read time vector
rm(time_units)

for (var in names(nc_2d$var)[c(3,4,6:12)]) {
  
#var <- "mld_rho"

array <- ncvar_get(nc_2d, var) # store the data in a 3-dimensional array
fillvalue <- ncatt_get(nc_2d, var, "_FillValue")
array[array == fillvalue$value] <- NA

array <- as.data.frame(t(array), xy=TRUE)
array <- as_tibble(array)
      
  gt_2d_part <- array %>%
  set_names(as.character(lat)) %>%
  mutate(date_time = t) %>%
  filter(date_time >= start_date & date_time <= end_date) %>% 
  gather("lat", "value", 1:length(lat)) %>%
  mutate(lat = as.numeric(lat)) %>%
  # filter(lat > low_lat, lat<high_lat) %>%
  # select(-lat) %>% 
  # group_by(date_time) %>% 
  # summarise_all(list(value=~mean(.,na.rm=TRUE))) %>%
  # ungroup() %>% 
  mutate(var = var)
     
  if (exists("gt_2d")) {
    gt_2d <- bind_rows(gt_2d, gt_2d_part)
    } else {gt_2d <- gt_2d_part} 

rm(array, fillvalue, gt_2d_part)

}

nc_close(nc_2d)
rm(nc_2d)

gt_2d_wide <- gt_2d %>% 
  mutate(value = round(value, 3)) %>% 
  pivot_wider(values_from = value, names_from = var) %>% 
  mutate(U_10 = round(sqrt(u10^2 + v10^2), 3)) %>% 
  select(-c(u10, v10))

gt_2d_long <- gt_2d_wide %>% 
  pivot_longer(3:10, names_to = "var", values_to = "value")

gt_2d_long %>% 
  write_csv((here::here("data/_summarized_data_files", file = "gt_2d_long.csv")))

gt_2d_wide %>% 
  write_csv((here::here("data/_summarized_data_files", file = "gt_2d_wide.csv")))

rm(t, var, gt_2d, gt_2d_long, gt_2d_wide, lat)

```


# Hovmoeller plots

```{r gt_hovmoeller_salt_temp_rho_age, fig.asp=2}

gt_2d_wide <- 
  read_csv((here::here("data/_summarized_data_files", file = "gt_2d_wide.csv")))

bin_SST = 2 
p_SST <- gt_2d_wide %>% 
  ggplot()+
  geom_contour_fill(aes(x=date_time, y=lat, z=SST),
                    breaks = MakeBreaks(bin_SST))+
  scale_fill_viridis_c(breaks = MakeBreaks(bin_SST),
                       guide = "colorstrip",
                       name = "SST (°C)",
                       option = "magma")+
  coord_cartesian(expand = 0)+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank())

bin_wind = 2 
p_wind <- gt_2d_wide %>% 
  ggplot()+
  geom_contour_fill(aes(x=date_time, y=lat, z=U_10),
                    breaks = MakeBreaks(bin_wind))+
  scale_fill_scico(palette="davos",
                   breaks = MakeBreaks(bin_wind),
                   guide = "colorstrip",
                   name = "Wind (m/s)")+
  coord_cartesian(expand = 0)+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank())

bin_rho = 5 
p_rho <- gt_2d_wide %>% 
  ggplot()+
  geom_contour_fill(aes(x=date_time, y=lat, z=mld_rho),
                    breaks = MakeBreaks(bin_rho))+
  scale_fill_scico(breaks = MakeBreaks(bin_rho),
                   guide = "colorstrip",
                   name = "mld_rho (m)",
                   palette = "tokyo",
                   direction = -1)+
  coord_cartesian(expand = 0)+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank())


bin_age1 = 5 
p_age1 <- gt_2d_wide %>% 
  ggplot()+
  geom_contour_fill(aes(x=date_time, y=lat, z=mld_age_1),
                    breaks = MakeBreaks(bin_age1))+
  scale_fill_scico(breaks = MakeBreaks(bin_age1),
                   guide = "colorstrip",
                   name = "mld_age_1 (m)",
                   palette = "tokyo",
                   direction = -1)+
  coord_cartesian(expand = 0)+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank())

bin_age5 = 5 
p_age5 <- gt_2d_wide %>% 
  ggplot()+
  geom_contour_fill(aes(x=date_time, y=lat, z=mld_age_5),
                    breaks = MakeBreaks(bin_age5))+
  scale_fill_scico(breaks = MakeBreaks(bin_age5),
                       guide = "colorstrip",
                       name = "mld_age_5 (m)",
                       palette = "tokyo",
                       direction = -1)+
  coord_cartesian(expand = 0)+
  theme(axis.title.x = element_blank())




p_SST / p_wind / p_rho / p_age1 / p_age5 

rm( p_SST , p_wind , p_rho , p_age1 , p_age5 )


```

# Daily regional mean

```{r gt_2d_area_daily_time_series, fig.asp=1.5}

gt_2d_long <- 
  read_csv((here::here("data/_summarized_data_files", file = "gt_2d_long.csv")))

gt_2d_long <- gt_2d_long %>% 
  mutate(area = "out",
         area = if_else(lat>54.15 & lat<54.55, "1.MEB", area),
         area = if_else(lat>54.8  & lat<55.25, "2.ARK", area),
         area = if_else(lat>57.5  & lat<58.5,  "4.EGS", area),
         area = if_else(lat>58.5  & lat<59,    "5.NGS", area),
         area = if_else(lat>59    & lat<59.8,  "6.WGF", area),
         area = if_else(lat>59.8  & lat<60,    "7.HGF", area))

gt_2d_area_long <- gt_2d_long %>% 
  filter(area != "out",
         var != "mld_tke") %>% 
  mutate(date = as.Date(date_time)) %>% 
  select(-c(date_time, lat)) %>% 
  group_by(area, date, var) %>% 
  summarise_all(list(~mean(.), ~sd(.), ~min(.), ~max(.)), na.rm=TRUE) %>% 
  ungroup()

gt_2d_area_long %>% 
  ggplot()+
  geom_line(aes(x=date, y=mean, col=area))+
  scale_color_brewer(palette = "Set1")+
  facet_grid(var~., scales = "free_y")+
  theme(axis.title.x = element_blank())+
  labs(y="Mean")

gt_2d_area_wide <- gt_2d_area_long %>% 
  pivot_wider(values_from = c(mean, sd, min, max), names_from = "var")

gt_2d_area_wide %>% 
  write_csv((here::here("data/_summarized_data_files", file = "gt_2d_area_wide.csv")))


```

```{r gt_2d_area_daily_time_series_plot, eval=FALSE}

gt_2d_reg_long %>% 
  ggplot()+
  geom_ribbon(aes(x=date, ymin=min, ymax=max, fill="min/max"), alpha=0.3)+
  geom_ribbon(aes(x=date, ymin=mean-sd, ymax=mean+sd, fill="SD"), alpha=0.3)+
  geom_line(aes(x=date, y=mean, col="mean"))+
  scale_fill_brewer(palette = "Set1", name="")+
  scale_color_manual(values = "black", name="")+
  facet_grid(var~area, scales = "free_y")+
  theme(axis.title.x = element_blank())+
  labs(y="value")

ggsave(here("docs/figure/getm.Rmd", "getm_var_area_time_series.pdf"),
       width = 15, height = 12)
```

